# Generated by Django 3.1.1 on 2020-10-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorite',
            new_name='favorites',
        ),
    ]
